@EventSouring_HostAddress = https://localhost:7033
@PackageId = 2e80acca-6bac-4b13-b59c-e6d75850eab3
@CartId = f58bc7d8-2c78-4ed6-bdd3-dec9c53bf95f

GET {{EventSouring_HostAddress}}/packages/{{PackageId}}


###

POST {{EventSouring_HostAddress}}/packages

###

POST {{EventSouring_HostAddress}}/packages/{{PackageId}}/load?cartId={{CartId}}
Content-Type: application/json

###



POST {{EventSouring_HostAddress}}/packages/{{PackageId}}/begindelivery
Content-Type: application/json


###

