@EventSouring_HostAddress = https://localhost:7033
@PackageId = 9a7d8e82-c7f4-4217-b4f9-7d8e90d5cb2c
@CartId = f58bc7d8-2c78-4ed6-bdd3-dec9c53bf95f

GET {{EventSouring_HostAddress}}/packages/{{PackageId}}


###

POST {{EventSouring_HostAddress}}/packages

###

POST {{EventSouring_HostAddress}}/packages/{{PackageId}}/load?cartId={{CartId}}
Content-Type: application/json

###



POST {{EventSouring_HostAddress}}/packages/{{PackageId}}/begindelivery
Content-Type: application/json


###

